import reflex as rx


def make_imagebox(img_path: str, img_kwargs: dict = None) -> rx.Component:
    """Helper function that creates a general box component for an image.
    Images contained within the box generated by this function
    will share the same formatting to have a general consistency across
    the site. Optionally these defaults can be overriden using the img_kwargs
    argument.

    Parameters
    ----------
    img_path : str
        path to your image. This assumes images are stored in assets/
    img_kwargs : dict, optional
        override default image styles used by this function, by default None

    Returns
    -------
    rx.Component
        A basic box component that contains and image
    """
    if not img_kwargs:
        img_kwargs = dict(
            border_radius="1em", align="center", margin="1em", width="90%"
        )

    return rx.box(
        rx.image(img_path, **img_kwargs),
        width="60%",
    )
